version: "3"

services:
  with-docker-multi-env-development:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    image: with-docker-multi-env-development
    # volumes:
    #   - ../../:/app
    #   - /app/node_modules
    #   - /app/.next
    ports:
      - "3001:3000"
